# Generated by Django 2.2.4 on 2019-08-03 02:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tags', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter the title of your article', max_length=100, unique=True, verbose_name='Titre')),
                ('slug', models.SlugField(editable=False, max_length=100, unique=True)),
                ('image', models.FileField(help_text='Choose the featured image of your article', upload_to='', verbose_name='Image liée')),
                ('content', models.TextField(help_text='Enter the content of your article', max_length=255, verbose_name='Contenu')),
                ('like', models.IntegerField(editable=False)),
                ('meta_description', models.TextField(help_text="Entrer the meta description of your article. It's like a resume of his content", max_length=255, verbose_name='Méta description')),
                ('created_at', models.DateField(auto_now=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('published_at', models.DateField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=10)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('categories', models.ManyToManyField(help_text='Choose one or more categories for the article', to='categories.Categorie', verbose_name='Catégorie')),
                ('tags', models.ManyToManyField(help_text='Choose one or more tags for the article', to='tags.Tag', verbose_name='Tags')),
            ],
            options={
                'ordering': ('-published_at',),
            },
        ),
    ]
