name_help_text="Enter the title of your article"
content_help_text="Enter the content of your article"
meta_description_help_text="Entrer the meta description of your article. It's like a resume of his content"
image_help_text ="Choose the featured image of your article"
status_help_text = "Please choose a status for the article"
categories_help_text = "Choose one or more categories for the article"
tags_help_text = "Choose one or more tags for the article"
