name_verbose_name="Titre"
content_verbose_name="Contenu"
meta_description_verbose_name="Méta description"
image_verbose_name ="Image liée"
status_verbose_name = "Status"
categories_verbose_name = "Catégorie"
tags_verbose_name = "Tags"
